### ISSUE TITLE
profile-analyze.py could look in blorbs for gameinfo.dbg

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/glulxe#9]
Would make it slightly easier to distribute profiling test builds (and the instructions for how to run it).

**Comment by erkyrath** [comment]
True.

What should the convention for this be? I don't think we have one, except that Quixe and CheapGlulxe can both take a config parameter for "what number DATA chunk contains the debug data". (Neither has been used beyond proof-of-concept.)

Is it time to define a specific Blorb chunk for this?

**Comment by curiousdannii** [comment]
An argument would be the easiest probably.

I don't think a new kind of blorb chunk is needed. It's not a disaster if it can't be found for some reason. But if there was to be a new blorb chunk it should be extensible so that it can cover this debug data as well as custom css files etc., anything which could be useful but which the game itself wouldn't control.

**Comment by erkyrath** [comment]
Blorb is itself extensible and available to the interpreter. So different features should have different chunk types. I only proposed DATA for the debug chunk because... actually I don't remember. It might have been the easiest option to test, is all.

(DATA is the only chunk type directly accessible by *game code*, as opposed to interpreter code. I don't think that's a meaningful win for debug data, or for CSS etc.)

**Comment by erkyrath** [comment]
I'm currently looking at a plan where the `Dbug` chunk in the blorb contains the gameinfo.dbg data.

**Comment by erkyrath** [comment]
Done.
